#!/bin/bash
n_dense=512
python3 train.py --model vgg16 --top chollet --n_dense $n_dense --train_top
python3 train.py --model vgg16 --top waya --n_dense $n_dense --train_top
python3 train.py --model vgg16 --top linear --n_dense $n_dense --train_top
python3 train.py --model vgg16 --top test --n_dense $n_dense --train_top --dropout
n_dense=2048
python3 train.py --model vgg16 --top chollet --n_dense $n_dense --train_top
python3 train.py --model vgg16 --top waya --n_dense $n_dense --train_top
python3 train.py --model vgg16 --top linear --n_dense $n_dense --train_top
python3 train.py --model vgg16 --top test --n_dense $n_dense --train_top --dropout